{{- if or .Values.pulse.apiKey (or .Values.aws.credentials.accessKeyId .Values.aws.credentials.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qpoint.fullname" . }}-credentials
  labels:
    {{- include "qpoint.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pulse.apiKey }}
  pulse-api-key: {{ .Values.pulse.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.aws.credentials.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.credentials.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.aws.credentials.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.credentials.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}
